/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StoreRouteImport } from './routes/store'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminDownloadsRouteImport } from './routes/admin/downloads'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminRedeemRouteImport } from './routes/admin/redeem'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardDownloadsRouteImport } from './routes/dashboard/downloads'
import { Route as DashboardPurchasesRouteImport } from './routes/dashboard/purchases'
import { Route as DashboardRedeemRouteImport } from './routes/dashboard/redeem'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDownloadsRoute = AdminDownloadsRouteImport.update({
  id: '/admin/downloads',
  path: '/admin/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRedeemRoute = AdminRedeemRouteImport.update({
  id: '/admin/redeem',
  path: '/admin/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDownloadsRoute = DashboardDownloadsRouteImport.update({
  id: '/dashboard/downloads',
  path: '/dashboard/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPurchasesRoute = DashboardPurchasesRouteImport.update({
  id: '/dashboard/purchases',
  path: '/dashboard/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRedeemRoute = DashboardRedeemRouteImport.update({
  id: '/dashboard/redeem',
  path: '/dashboard/redeem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/store': typeof StoreRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/redeem': typeof AdminRedeemRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/purchases': typeof DashboardPurchasesRoute
  '/dashboard/redeem': typeof DashboardRedeemRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/store': typeof StoreRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/redeem': typeof AdminRedeemRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/purchases': typeof DashboardPurchasesRoute
  '/dashboard/redeem': typeof DashboardRedeemRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/store': typeof StoreRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/redeem': typeof AdminRedeemRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/purchases': typeof DashboardPurchasesRoute
  '/dashboard/redeem': typeof DashboardRedeemRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/store'
    | '/admin/activity'
    | '/admin/content'
    | '/admin/downloads'
    | '/admin/notifications'
    | '/admin/products'
    | '/admin/redeem'
    | '/admin/users'
    | '/dashboard/downloads'
    | '/dashboard/purchases'
    | '/dashboard/redeem'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/store'
    | '/admin/activity'
    | '/admin/content'
    | '/admin/downloads'
    | '/admin/notifications'
    | '/admin/products'
    | '/admin/redeem'
    | '/admin/users'
    | '/dashboard/downloads'
    | '/dashboard/purchases'
    | '/dashboard/redeem'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/store'
    | '/admin/activity'
    | '/admin/content'
    | '/admin/downloads'
    | '/admin/notifications'
    | '/admin/products'
    | '/admin/redeem'
    | '/admin/users'
    | '/dashboard/downloads'
    | '/dashboard/purchases'
    | '/dashboard/redeem'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StoreRoute: typeof StoreRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDownloadsRoute: typeof AdminDownloadsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRedeemRoute: typeof AdminRedeemRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DashboardDownloadsRoute: typeof DashboardDownloadsRoute
  DashboardPurchasesRoute: typeof DashboardPurchasesRoute
  DashboardRedeemRoute: typeof DashboardRedeemRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/downloads': {
      id: '/admin/downloads'
      path: '/admin/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AdminDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/redeem': {
      id: '/admin/redeem'
      path: '/admin/redeem'
      fullPath: '/admin/redeem'
      preLoaderRoute: typeof AdminRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/downloads': {
      id: '/dashboard/downloads'
      path: '/dashboard/downloads'
      fullPath: '/dashboard/downloads'
      preLoaderRoute: typeof DashboardDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/purchases': {
      id: '/dashboard/purchases'
      path: '/dashboard/purchases'
      fullPath: '/dashboard/purchases'
      preLoaderRoute: typeof DashboardPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/redeem': {
      id: '/dashboard/redeem'
      path: '/dashboard/redeem'
      fullPath: '/dashboard/redeem'
      preLoaderRoute: typeof DashboardRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StoreRoute: StoreRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDownloadsRoute: AdminDownloadsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRedeemRoute: AdminRedeemRoute,
  AdminUsersRoute: AdminUsersRoute,
  DashboardDownloadsRoute: DashboardDownloadsRoute,
  DashboardPurchasesRoute: DashboardPurchasesRoute,
  DashboardRedeemRoute: DashboardRedeemRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
